services:
  api:
    build: 
      context: ./
    environment:
      - AWS_REGION=us-east-1
      - DSQL_ENDPOINTS=4iabtwnq2j55iez4j4bkykghgm.dsql.us-east-1.on.aws,s4abtwnq2jebk7aj6vhlsb2coi.dsql.us-east-2.on.aws
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s